name: Unity Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.3.11f1-android-3.2.2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Activate Unity and Check Version
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          # Tworzymy folder na licencję tam, gdzie Unity go szuka w Linuxie
          mkdir -p /root/.local/share/unity3d/Unity/
          # Wrzucamy zawartość sekretu do pliku
          echo "$UNITY_LICENSE" | tr -d '\r' > /root/.local/share/unity3d/Unity/Unity_lic.ulf
          
          # Odpalamy Unity, żeby sprawdzić czy licencja działa
          unity-editor \
            -logFile /dev/stdout \
            -batchmode \
            -nographics \
            -projectPath . \
            -quit

      - name: Export Log if failed
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: unity-logs
          path: ./*.log
